# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 十年磨一剑
description: 天行健君子以自强不息，地势坤君子以厚德载物
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jshome.me" # the base hostname & protocol for your site
github_username:  xuanxiao2013

# Build settings
markdown: kramdown